# Developed by Pavan Gajjala – https://github.com/pavangajjala
# Licensed under Apache 2.0. Unauthorized removal of attribution is prohibited.

name: VaultScan GitHub Action
description: VaultScan is a fast, offline-first secret scanner for DevOps and CI/CD pipelines.
  Detect secrets before they leak — works locally or in GitHub Actions.

  🔐 Pro version coming soon with team reports, API, dashboards.
  📬 Join waitlist: https://bit.ly/vaultscan-pro

branding:
  icon: shield
  color: blue
  
runs:
  using: composite
  steps:
    - name: Clone VaultScan
      run: |
        git clone https://github.com/pavangajjala/vaultscan-community.git
      shell: bash

    - name: Install VaultScan dependencies
      run: |
        pip install -r vaultscan-community/requirements.txt
      shell: bash

    - name: Run VaultScan
      run: |
        python -m vaultscan.main --path ${{ github.workspace }} --verbose
      working-directory: vaultscan-community
      shell: bash