# Developed by Pavan Gajjala – https://github.com/pavangajjala
# Licensed under Apache 2.0. Unauthorized removal of attribution is prohibited.

name: VaultScan GitHub Action (Python)
description: Run VaultScan community Edition v1.2 to detect secrets and credentials in your repository.

branding:
  icon: shield
  color: blue
  
runs:
  using: composite
  steps:
    - name: Clone VaultScan
      run: |
        git clone https://github.com/pavangajjala/vaultscan-community.git
      shell: bash

    - name: Install VaultScan dependencies
      run: |
        pip install -r vaultscan-community/requirements.txt
      shell: bash

    - name: Run VaultScan
      run: |
        python -m vaultscan.main --path ${{ github.workspace }} --verbose
      working-directory: vaultscan-community
      shell: bash
