name: VaultScan GitHub Action (Python)
description: Run VaultScan via Python for secret detection

runs:
  using: composite
  steps:
    - name: Install VaultScan dependencies
      run: |
        pip install -r requirements.txt
      shell: bash

    - name: Run VaultScan
      run: |
        python -m vaultscan.main --path . --verbose
      shell: bash