name: VaultScan GitHub Action (Python)
description: Run VaultScan via Python for secret detection

runs:
  using: composite
  steps:
    - name: Install VaultScan directly from GitHub
      run: |
        pip install git+https://github.com/pavangajjala/vaultscan-community.git
      shell: bash

    - name: Run VaultScan
      run: |
        python -m vaultscan.main --path . --verbose
      shell: bash